# Generated by Django 3.2.3 on 2021-05-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(default='', max_length=50),
        ),
    ]
