# Generated by Django 3.2.3 on 2021-06-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_diary_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='', upload_to='diaryImg/'),
        ),
    ]
